config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :schools

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :school
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :classrooms, dependent: :destroy
	#Dependent destroy will delete all record
	#in the has many association
	#THIS IS BEST PRACTICE
	has_one :address, dependent: :destroy

	#validations go here
	#second line of defense for bad data
	validates_presence_of :name #most used
	validates_uniqueness_of :name #most used
	#validates :name, inclusion: {in ['DLP', 'CodesSchool', 'DevMountain']}
	#size
	#length
	# validates :name, length: {minimum: 2, maximum: 50}
	#numericality
	# validates :year_built, numericality: {only_integer: true}
	#uniqueness

	before_create :default_year_built
	#callbacks go here
	private

	def default_year_built
		self.year_built = '2016' unless self.year_built
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
  	# GET - show all the schools
  	@schools = School.all
  end

  def show
  	# GET - show a single school
  	@school = School.find(params[:id])
  end

  def edit
  	# GET - show a form to edit a school
  	@school = School.find(params[:id])
  end

  def update
  	# PUT - update records in a school
  	@school = School.find(params[:id])
  	if @school.update(school_params)
  		#updated school sucessfully
  		redirect_to school_path(@school)
  	else
  		#something went wrong
  		render :edit
  	end
  end

  def new
  	# GET - show a form to create a new school
  	@school = School.new
  end

  def create
  	# POST - creating a new school record in the db
  	@school = School.new(school_params)
  	if @school.save
  		#successful save in db
  		redirect_to schools_path
  	else
  		#something went wrong
  		render :new
  	end
  end

  def destroy
  	# DELETE - delete a single school out of db
  	School.find(params[:id]).destroy
  	redirect_to schools_path
  end

  private

  	def school_params
  		params.require(:school).permit(:name, :yearbuilt)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DplRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :year_built %>
	<%= f.text_field :year_built %>
	<%= f.submit %>
<% end %>

<!--
  <form action='/schools' method='POST'>
    <label>Name</label>
    <input type='text' name='school[name]' />

    <label>Year Built</label>
    <input type='text' name='school[year_built]' />

    <input type='submit' />
  </form> -->

app/views/schools/edit.html.erb
<h1>Editing School: <%= @school.name %></h1>

<%= render(partial: 'form') %>

app/views/schools/index.html.erb
<h1>All Schools</h1>
<br />

<!-- what does the user see if there are no schools? -->
<!-- what does the user see if there are schools? -->
<!-- add a link or button to create a new school -->

<% if @schools.any? %>
	<!-- loop the schools and display linkds to each one -->
	<ul>
	<% @schools.each do |school| %>
	<li>
		<%= link_to school.name, school_path(school) %>
		<!-- <a href='/school/:id'>Neumont</a> -->
	</li>
	<% end %>
	</ul>
<% else %>
		<h3>No schools found. Please create one.</h3>
<% end %>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>Create a New School</h1>
<br />

<%= render(partial:'form') %>

app/views/schools/show.html.erb
<h1><%= @school.name %> Info:</h1>
<br />
<h3>
	This school was built in: <%= @school.year_built %>
</h3>

<%= link_to 'Edit', edit_school_path(@school) %>

<%= link_to 'Delete', school_path(@school), method: :delete %>

<%= link_to 'All Schools', schools_path %>